### ISSUE TITLE
24 hour time format possible

### ISSUE THREAD

**Issue by Seruschl** [virejdasani/LuminousTime#1]
Hi and thanks for this great "widget"

is it maybe possible to have an 24 hour time format?? I haven't figured it out to build it by myself and hope that you maybe have an idea how to do it.

**Comment by virejdasani** [comment]
Sure thing. I'll do it soon and let you know here :)

**Comment by virejdasani** [comment]
@Seruschl I have added the 24hr format zip file in the [releases tab](https://github.com/virejdasani/LuminousTime/releases/tag/v1.0.0). 
You can download it from there or directly by clicking [here](https://github.com/virejdasani/LuminousTime/releases/download/v1.0.0/luminous-time.24hr.widget.zip) 
Also, let me know if there is anything else I should add/modify/delete 👍
